### ISSUE TITLE
Is it possible to add information on a leak sensor ?

### ISSUE THREAD

**Issue by BenouGui** [ebaauw/homebridge-ups#11]
Hello, 

Is it possible to add information on a leak sensor so that we receive a notification in the event of a power outage?

Thanks in advance

**Comment by ebaauw** [comment]
It is technically possible to add a _Leak_ or _Smoke_ sensor to the UPS accessory.  I did so for Homebridge RPi (smoke sensor for throttling and /or under voltage) and Homebridge WS (leak sensor for rain/snow).  I do foresee a couple of issues, though:
- Since iOS 15, HomeKit uses special alarm notifications for these sensors which cannot be silenced.  Maybe using a motion or contact sensor would be better, as these still cause regular notifications;
- It will likely cause Eve no longer to display the History, thinking the device is an Eve Water Guard or Eve Smoke instead of an Eve Energy.  As a workaround, I could create a separate accessory for the leak or smoke sensor, but that will count against the max 150 accessories per HomeKit bridge.
- Note that not only Homebridge, but also your Internet connection, and possibly your home hub, must still be working after a power outage to send the notification.  I’m not sure about the home hub, but you do definitely need it to look at the accessory, once you receive the notification (over mobile data).  In other words: you would need the UPS to power the Homebridge server, Internet router, AppleTV or HomePod, and any networking equipment in between these.

**Comment by BenouGui** [comment]
I currently already have a homepod on ups with modem router etc because I use for security too.
And precisely the notification without silence is precisely what I am looking for.

for me the history does not interest me because I already use grafana to log my info

a solution can be an option to export the ups info to mqtt, I create the leak sensors myself

thanks for the info

**Comment by ebaauw** [comment]
I have no experience with MQTT.  Also, I don't think it would make sense to use a Homebridge plugin to connect `nut` to MQTT.
