### ISSUE TITLE
Switch to contact sensor instead of outlet with a stateless switch for mute.

### ISSUE THREAD

**Issue by sapireli** [ebaauw/homebridge-ups#17]
Now with ios 17 having built-in native history for contact sensors, i think it makes sense to use that instead of the outlet (and eve history). The other benefit is support for activity notifications which aren't supported on outlet. I think this would be a huge enhancement with the other being a mute stateless switch instead of an outlet. I can probably do this in a pull request if you think it makes sense.

**Comment by ebaauw** [comment]
> Now with ios 17 having built-in native history for contact sensors

Huh?  Where do I find this?  Do you have documentation and/or screenshots?

**Comment by sapireli** [comment]
here it is: https://support.apple.com/en-us/HT213743 
@ebaauw

**Comment by sapireli** [comment]
activity history is supported for garage doors, door locks, security systems, and **contact sensors**.

**Comment by ebaauw** [comment]
Ah yes, the Activity History_ under _Security_.  That seems to be a Home special, not available to other HomeKit apps.  I don't like that, as it lacks any graphical display, but it works in parallel to Eve history (for contact sensors).

_Outlet_ seems to be the natural choice, for providing combined history for _On/Off_ and _Consumption_, .  I agree, mapping the UPS state to _On/Off_ doesn't make much sense, especially since the UPS state is read-only.  Also, I like the idea of push notification when my UPS switches to battery or reports an alarm (last time that happened, I heard the beep on the device, but hadn't noticed the _Status Fault_).

I don't think I've tried combining contact sensor and consumption history in a single accessory before.  Eve generally doesn't like combined history for sensors and actuators (lights, switches, outlets, where consumption is reported), but it wouldn't hurt to try.  Combined history for stateless switches with anything else doesn't work, as Eve thinks the device is an Eve button.

**Comment by sapireli** [comment]
another option: add a contact sensor for ups status, and notifications, limit the outlet to enabling/disabling the beeper, and consumption history?

**Comment by ebaauw** [comment]
In v1.2.0.

**Comment by sapireli** [comment]
Erik you are the man. I tested works perfect. Thank you so much!!! Amazing.
