### ISSUE TITLE
log level errors and heartbeat errors

### ISSUE THREAD

**Issue by sapireli** [ebaauw/homebridge-ups#19]
Hi Erik, 
i'm hoping you can help me figure out these two errors i'm seeing, perhaps this is something simple:
1. Camera UPS: error: heartbeat error: send in progress >> I see a lot of these for two older tripplite ups models
2.Camera UPS: error: TypeError: Cannot redefine property: logLevel >> i see this error for all the connected ups(s) that i changed the log level for.

**Comment by ebaauw** [comment]
Please list the full error messages, including the stack trace.

Ad 1.  The NUT server only handles one request at a time.  This error is issued when Homebridge UPS tries to poll the NUT server, while there's still a response pending.  I would need to see a full debug log to see what's happening.

Ad 2.  I haven't seen this one before.  Did you recently upgrade Homebridge UPS?  Maybe it's related to accessories being cached by an older version and loaded from cache by a newer version?  Again would need to see a full debug log to understand what's going on.

Make sure to run Homebridge in debug mode and set _LogLevel_ to 2 when caputuring a full debug log.  I would need to see the log from Homebridge startup to the point where the error occurs.

**Comment by sapireli** [comment]
Thank you so much for taking the time. Please find attached the full log.
The stack trace is below:

`[11/30/2023, 10:30:22 PM] [UPS] upspi: error: TypeError: Cannot redefine property: logLevel
    at UpsHost.init (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:80:18)
    at UpsPlatform.init (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:107:7)`

and

`[11/30/2023, 10:30:23 PM] [UPS] Homebridge: error: TypeError: Cannot redefine property: logLevel
    at UpsHost.init (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:80:18)

[homebridge_log.txt](https://github.com/ebaauw/homebridge-ups/files/13520361/homebridge_log.txt)
`

**Comment by sapireli** [comment]
FYI it seems the error #1 heartbeat was resolved when i moved the plugin to a child bridge.

Error #2 the loglevel type error is still occuring.

**Comment by ebaauw** [comment]
Thanks.  The errors are related to managing multiple UPS devices from a single host.  I do have multiple UPS devices, but they're connected to different hosts (two NAS devices, and one Raspberry Pi).  Since these are all running production, I'm not going to change my setup for testing.  It looks like I half considered multiple devices per host, but without any testing that's bound to be broken.

Could you please list the output of `ups info` and of `ups -H upspi.lan info`, so I can see how the devices are reported?

**Ad 1.**

Running Homebridge UPS in a child bridge gives it its own NodeJS process.  Consequently, it's no longer impacted by other plugins doing blocking requests.  I does require more resources, though, notably memory.  Running multiple child bridges on a 512 MB Pi B might be challeging.  Better keep an eye on your swapfile usage (through `htop`); in my experience, Raspberry Pi OS stalls when the swapfile is full, and the default 100MB is a joke.

I'm still seeing some heartbeat errors in the log, preceded by some drift warnings.  The load on startup might be a bit too much for the Pi B, but it looks like everything ends up OK eventually.

**Ad 2.**

The `TypeError` is a bug alright.  I'm setting a `LogLevel` property on the `UpsHost` instance, linked to the `LogLevel` characteristic of the `UpsService` instance.  Since you have multiple UPS devices connected to the same host, this goes wrong for the second device.  As the error is unchecked, accessories for the third, fourth, and more devices aren't created, and the host won't signal it's initialised.

**Comment by clayton256** [comment]
I'm following this. I have a RPi with to UPSes and I'm seeing the same log lines.
Running upsc shows:
```
# upsc -l 10.0.1.199 
Init SSL without certificate database
nutdev1
nutdev2
```

**Comment by sapireli** [comment]
Thank you Erik 🙏
